### ISSUE TITLE
Embedded Null Character

### ISSUE THREAD

**Issue by DeiTux** [rferrazz/pyqt4topyqt5#9]
Command Prompt:

C:\Users\user\Desktop\_DEV\qt4toqt5>pyqt4topyqt5.py about.pyc -o 11.pyc
Traceback (most recent call last):
  File "C:\Users\user\Desktop\_DEV\qt4toqt5\pyqt4topyqt5.py", line 2732, in <module>
    main = Main(sys.argv)
  File "C:\Users\user\Desktop\_DEV\qt4toqt5\pyqt4topyqt5.py", line 2499, in __init__
    self.prepare_changes(self.followlinks)
  File "C:\Users\user\Desktop\_DEV\qt4toqt5\pyqt4topyqt5.py", line 2548, in prepare_changes
    self.copy_files(self.destdir, subdirs, files)
  File "C:\Users\user\Desktop\_DEV\qt4toqt5\pyqt4topyqt5.py", line 2631, in copy_files
    if not os.path.isfile(f):
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
ValueError: stat: embedded null character

**Comment by rferrazz** [comment]
which python version are you using?

**Comment by DeiTux** [comment]
@rferrazz Right now, I was trying to run this with 3.5.3
